### ISSUE TITLE
Fails to compile with Clojure 1.10.0-alpha5

### ISSUE THREAD

**Issue by seancorfield** [ptaoussanis/nippy#108]
I'm not sure whether this is a bug in the new ASM stuff in Alpha 5 or something incompatible in Nippy. If you add a `:1.10-5` profile that depends on `org.clojure/clojure "1.10.0-alpha5"` and run `lein with-profile 1.10-5 test` you get this compiler failure:
```
Exception in thread "main" java.lang.IllegalArgumentException, compiling:(taoensso/nippy.clj:1108:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7017)
	at clojure.lang.Compiler.analyze(Compiler.java:6780)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6998)
	at clojure.lang.Compiler.analyze(Compiler.java:6780)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
	at clojure.lang.Compiler.analyze(Compiler.java:6780)
	at clojure.lang.Compiler.analyze(Compiler.java:6736)
	at clojure.lang.Compiler.eval(Compiler.java:7073)
	at clojure.lang.Compiler.load(Compiler.java:7521)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6629.invoke(core.clj:6061)
	at clojure.core$load.invokeStatic(core.clj:6060)
	at clojure.core$load.doInvoke(core.clj:6044)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5863)
	at clojure.core$load_one.invoke(core.clj:5858)
	at clojure.core$load_lib$fn__6574.invoke(core.clj:5903)
	at clojure.core$load_lib.invokeStatic(core.clj:5902)
	at clojure.core$load_lib.doInvoke(core.clj:5883)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5940)
	at clojure.core$load_libs.doInvoke(core.clj:5924)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5962)
	at clojure.core$require.doInvoke(core.clj:5962)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at user$eval227.invokeStatic(form-init2293195735890223451.clj:1)
	at user$eval227.invoke(form-init2293195735890223451.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7069)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.load(Compiler.java:7521)
	at clojure.lang.Compiler.loadFile(Compiler.java:7459)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException
	at clojure.asm.commons.GeneratorAdapter.cast(GeneratorAdapter.java:785)
	at clojure.lang.Compiler$CaseExpr.emitExprForInts(Compiler.java:8812)
	at clojure.lang.Compiler$CaseExpr.doEmit(Compiler.java:8735)
	at clojure.lang.Compiler$CaseExpr.emit(Compiler.java:8712)
	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:6151)
	at clojure.lang.Compiler$LetExpr.doEmit(Compiler.java:6510)
	at clojure.lang.Compiler$LetExpr.emit(Compiler.java:6460)
	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:6151)
	at clojure.lang.Compiler$TryExpr.emit(Compiler.java:2212)
	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:6151)
	at clojure.lang.Compiler$LetExpr.doEmit(Compiler.java:6510)
	at clojure.lang.Compiler$LetExpr.emit(Compiler.java:6460)
	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:6151)
	at clojure.lang.Compiler$ObjMethod.emitBody(Compiler.java:5851)
	at clojure.lang.Compiler$FnMethod.doEmitStatic(Compiler.java:5515)
	at clojure.lang.Compiler$FnMethod.emit(Compiler.java:5480)
	at clojure.lang.Compiler$FnExpr.emitMethods(Compiler.java:3944)
	at clojure.lang.Compiler$ObjExpr.compile(Compiler.java:4580)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4106)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7008)
	... 51 more
```
If you use Clojure 1.10.0-alpha4, it compiles and all the tests pass.

**Comment by seancorfield** [comment]
I've narrowed this down to `enc/case-eval` so it's an Encore-related issue, not Nippy. As I narrow it down further, I'll open a JIRA issue for Clojure and a related issue in Encore if I can figure out the specific cause.

**Comment by seancorfield** [comment]
I've narrowed it down to an issue in Clojure itself. Sorry for the noise!

**Comment by ptaoussanis** [comment]
Hi Sean, thanks a lot for following up (and digging to find the cause)!

Reference for others: Sean opened [CLJ-2367](https://dev.clojure.org/jira/browse/CLJ-2367) with additional details. Seems like a possible issue with updated ASM library.
